### ISSUE TITLE
[BUG] libcamera-vid(rpicam-vid) ignore "--segment" flag

### ISSUE THREAD

**Issue by arsenicks** [raspberrypi/rpicam-apps#638] opened 2024-02-04 00:17 UTC
**Describe the bug**
Trying to record a X minutes video(using -t X)  and want the recording to be split  in different segment so I use the "--segment X" flag. The video get recorded but in only one file and it stop after the first segment. The program seems to get the parameter as you will see in the verbose mode but recording doesn't get split and stop at the first part. 

No error printed just that the timeout has been reached but it's not the timeout that has been reach but the "segment timeout" it should write the file and start another one according to the documentation: "This option causes the video recording to be split across multiple files where the parameter gives the approximate duration of each file in milliseconds."

**Bug report**
[segmentbug.txt](https://github.com/raspberrypi/rpicam-apps/files/14154644/segmentbug.txt)

**Additional context**
For some reason the bug report tool doesn't report the correct command(the tool show the date fullfilled) so here it is just in case that part could cause any problem:
`rpicam-vid -t 100000 --segment 10000 -o "/nfs/riv/riv-pres-$(date +\%Y-\%m-\%d-\%H.\%M)-%04d.mp4" -n --width 1536 --height 864 --tuning-file /usr/share/libcamera/ipa/rpi/vc4/imx708_wide_noir.json --hdr --libav-audio --audio-source alsa --audio-device pseye_cap  --codec libav --libav-format mp4 --audio-codec alac -v 2`

Thanks

**Comment by naushir** [comment] 2024-02-05 08:56
This is a known issue. There was some bugs in the implementation that had to be reverted (see https://github.com/raspberrypi/rpicam-apps/issues/580). I've not had time to have a look again at this, but will do soon.

**Comment by naushir** [comment] 2024-02-05 08:57
Closing as a duplicate of https://github.com/raspberrypi/rpicam-apps/issues/580.

**Closed by naushir** 2024-02-05 08:57 UTC
